### ISSUE TITLE
Build failing due to invalid username / password

### ISSUE THREAD

**Issue by Syntaf** [Syntaf/travis-sphinx#25]
@lmignon I'm wondering if you might have any clues as to why your code is causing the repositories travis build to fail. Here's the output log from travis:

```
8.05s$ pip install $TRAVIS_BUILD_DIR
Processing /home/travis/build/Syntaf/travis-sphinx
Collecting sphinx (from travis-sphinx==2.0.0)
  Using cached Sphinx-1.6.5-py2.py3-none-any.whl
Collecting click (from travis-sphinx==2.0.0)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting ghp-import (from travis-sphinx==2.0.0)
Collecting imagesize (from sphinx->travis-sphinx==2.0.0)
  Using cached imagesize-0.7.1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages (from sphinx->travis-sphinx==2.0.0)
Collecting sphinxcontrib-websupport (from sphinx->travis-sphinx==2.0.0)
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx->travis-sphinx==2.0.0)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx->travis-sphinx==2.0.0)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx->travis-sphinx==2.0.0)
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Collecting docutils>=0.11 (from sphinx->travis-sphinx==2.0.0)
  Using cached docutils-0.14-py2-none-any.whl
Collecting typing; python_version < "3.5" (from sphinx->travis-sphinx==2.0.0)
  Using cached typing-3.6.2-py2-none-any.whl
Collecting requests>=2.0.0 (from sphinx->travis-sphinx==2.0.0)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages (from sphinx->travis-sphinx==2.0.0)
Collecting babel!=2.0,>=1.3 (from sphinx->travis-sphinx==2.0.0)
  Using cached Babel-2.5.1-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx->travis-sphinx==2.0.0)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx->travis-sphinx==2.0.0)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx->travis-sphinx==2.0.0)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0.0->sphinx->travis-sphinx==2.0.0)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.0.0->sphinx->travis-sphinx==2.0.0)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx->travis-sphinx==2.0.0)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx->travis-sphinx==2.0.0)
Building wheels for collected packages: travis-sphinx
  Running setup.py bdist_wheel for travis-sphinx: started
  Running setup.py bdist_wheel for travis-sphinx: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/6d/3a/4a/7593105f4b79af365806637562db434807ed14714a310b547b
Successfully built travis-sphinx
Installing collected packages: imagesize, sphinxcontrib-websupport, Pygments, snowballstemmer, alabaster, docutils, typing, chardet, certifi, urllib3, idna, requests, pytz, babel, MarkupSafe, Jinja2, sphinx, click, ghp-import, travis-sphinx
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.5.1 certifi-2017.7.27.1 chardet-3.0.4 click-6.7 docutils-0.14 ghp-import-0.5.5 idna-2.6 imagesize-0.7.1 pytz-2017.3 requests-2.18.4 snowballstemmer-1.2.1 sphinx-1.6.5 sphinxcontrib-websupport-1.0.1 travis-sphinx-2.0.0 typing-3.6.2 urllib3-1.22
1.20s$ travis-sphinx build --source=test/docs/source
Running Sphinx v1.6.5
making output directory...
loading translations [Python]... not available for built-in messages
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] index
reading sources... [100%] test
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 50%] index
writing output... [100%] test
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
The command "travis-sphinx build --source=test/docs/source" exited with 0.
0.58s$ travis-sphinx deploy
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/Syntaf/travis-sphinx.git/'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/ghp-import", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/ghp_import.py", line 242, in main
    git.check_call('push', opts.remote, opts.branch, '--force')
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/ghp_import.py", line 106, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'https://[secure]@github.com/Syntaf/travis-sphinx.git', 'gh-pages', '--force']' returned non-zero exit status 128
Error: /home/travis/virtualenv/python2.7.13/bin/ghp-import -p -f -n -r https://[secure]@github.com/Syntaf/travis-sphinx.git -m Update\ documentation doc/build
The command "travis-sphinx deploy" exited with 1.
cache.2
store build cache
```

**Comment by lmignon** [comment]
I'll be back tomorrow. I've limited access to internet for the moment.
Sorry. A possible cause is the miss of the gh_tokrn env variable....

**Comment by Syntaf** [comment]
Seems the build had not been ran in so long that my token expired. All fixed and build passing
