### ISSUE TITLE
Travis-CI: ModuleNotFoundError

### ISSUE THREAD

**Issue by pancetta** [Syntaf/travis-sphinx#39]
For some reason I get a ModuleNotFoundError [here](https://github.com/Syntaf/travis-sphinx/blob/master/travis_sphinx/build.py#L7), which is not caught by the try/except-block. This happens when my Sphinx version is below 1.7. 

More precisely, I get: 
> Traceback (most recent call last):
>  File "/home/travis/miniconda3/bin/travis-sphinx", line 7, in <module>
>  from travis_sphinx.main import main
>  File "/home/travis/miniconda3/lib/python3.6/site-packages/travis_sphinx/__init__.py", line 3, in <module>
>      from . import build
>  File "/home/travis/miniconda3/lib/python3.6/site-packages/travis_sphinx/build.py", line 7, in <module>
>      from sphinx.cmd.build import build_main
> ModuleNotFoundError: No module named 'sphinx.cmd'

Could you add ModuleNotFoundError to the except rule or is there something else going on here?

**Comment by Syntaf** [comment]
Thanks for the issue report! Unfortunately sphinx has been switching around their internal interface which leaves us playing catch up. 

What minor version of 1.7 are you using? We added support for 1.7 in https://github.com/Syntaf/travis-sphinx/issues/34 , I'm hoping they didn't change the internal interface _again_
